### PR TITLE
Fixed arrays

### LINKED ISSUE #11: CmakeList.txt isnt being generated
Hi, When i run:
  perl vcxproj2cmake.pl myproject1.vcxproj  "\Debug"

i get
Use of uninitialized value $add_dep in substitution (s///) at vcxproj2cmake.pl line 386.
Use of uninitialized value $add_dep in split at vcxproj2cmake.pl line 388.
$VAR1 = '..';
$VAR2 = '$(SolutionDir)x_other_libs';
$VAR3 = '.';
$VAR1 = 'package';
$VAR2 = 'Boost';
$VAR3 = 'package_upcase';
$VAR4 = 'BOOST';
$VAR1 = 'flter';
$VAR2 = 'Strategies\\something\\something';
$VAR3 = 'files';
$VAR4 = '';
$VAR1 = 'flter';
$VAR2 = 'interactions';
$VAR3 = 'files';
$VAR4 = '';
$VAR1 = 'flter';
$VAR2 = 'Strategies\\Other';
$VAR3 = 'files';
$VAR4 = '';
$VAR1 = 'files';
$VAR2 = '';
$VAR3 = 'flter';
$VAR4 = 'Strategies\\something\\thing\\somes';
$VAR1 = 'flter';
......
$VAR20 = '-DWIN32
        -D_DEBUG
        -D_CONSOLE';

but no file.
do i need to pipe it to a file or is something not being written correctly?

### PR DESCRIPTION
**Pull request by KalleDK**
fixes #11 #9

### CODE REVIEW

**Comment by KalleDK** [comment]
fixes #13

**Comment by KalleDK** [comment]
vcxproj2cmake_issue12  aatt  k-moeller.dk

**Comment by virtuald** [comment]
I checked out this PR, and it did not fix my problem with the vcxproj at https://github.com/rainers/cv2pdb.git :

    Not an ARRAY reference at vcxproj2cmake.pl line 44.

**Comment by Plusce** [comment]
@edit:

> hello, i got your repo (fix) but the problem persists:
> $ perl vcxproj2cmake.pl aa.vcxproj Release
> Not a HASH reference at vcxproj2cmake.pl line 150.

The same like me. Does anybody have any ideas how can I solve it? I would be so grateful.

**Pull request closed without merging**
